---
title: 'MCC: Generate Consistent AFP Data'
author: "MCC"
date: "8/21/2020"
output: html_document
---

#### Import libraries
```{r message=FALSE, warning=FALSE}
library(easypackages)
libraries("readr", "caret", "Boruta")
```


#### Load Data: AFP & Non-AFP Only
```{r message=FALSE, warning=FALSE}
afp <- read_csv("AFP11.csv",
                col_names = FALSE)
non_afp <- read_csv("Non-AFP11.csv", 
                    col_names = FALSE)
```

#### Generate Indicator Variable
```{r include=FALSE}
afp$X2 <- rep(1, 481)
non_afp$X2 <- rep(0, 9191)
all_afp <- rbind(afp, non_afp)
all_afp <- all_afp[,-1] 
factor(all_afp$X2, levels = c("0", "1"), labels = c("Neg", "Pos"))
```


#### Simple Splitting Based on the Outcome
```{r message=FALSE, warning=FALSE}
set.seed(3456)
trainIndex <- createDataPartition(all_afp$X2, 
                                  p = 0.8, 
                                  list = FALSE, 
                                  times = 1)

all_afp_train <- all_afp[ trainIndex,]
all_afp_test  <- all_afp[-trainIndex,]
```




















